spring:
  application:
    name: Elasticsearch
  elasticsearch:
    url: ${ELASTICSEARCH_URL:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:password}
    duration: 30s
    timeout: 30s
